# Generated by Django 5.2.8 on 2025-11-29 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Ready', 'Ready'), ('Preparing', 'Preparing'), ('Completed', 'Completed')], default='Pending', max_length=20),
        ),
    ]
