# Generated by Django 5.2.8 on 2025-12-05 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0004_menuitem_category_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='category',
            field=models.CharField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('snacks', 'Snacks'), ('bevarages', 'Bevarages')], default='General', max_length=20),
        ),
    ]
