# Generated by Django 5.2.8 on 2025-12-12 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0005_alter_menuitem_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Inventory',
        ),
    ]
