# Generated by Django 5.2.8 on 2025-12-12 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0006_delete_inventory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Preparing', 'Preparing'), ('Ready', 'Ready'), ('Picked Up', 'Picked Up'), ('Paid', 'Paid')], default='Pending', max_length=20),
        ),
    ]
