# Generated by Django 5.2.8 on 2025-12-12 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0007_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='category',
            field=models.CharField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('snacks', 'Snacks'), ('chocolates', 'Chocolates'), ('bevarages', 'Bevarages')], default='General', max_length=20),
        ),
    ]
