# Generated by Django 5.2.8 on 2025-12-13 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0008_alter_menuitem_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='category',
            field=models.CharField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('snacks', 'Snacks'), ('chocolates', 'Chocolates'), ('beverages', 'Beverages')], default='General', max_length=20),
        ),
    ]
