# Generated by Django 5.2.8 on 2025-11-20 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('canteen', '0002_orderitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='items',
        ),
    ]
