# Generated by Django 5.2.8 on 2025-11-29 06:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0002_alter_order_status'),
        ('canteen', '0005_alter_order_total_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminpanel.menuitem'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Ready', 'Ready'), ('Preparing', 'Preparing'), ('Completed', 'Completed')], default='Pending', max_length=20),
        ),
        migrations.DeleteModel(
            name='MenuItem',
        ),
    ]
