# Generated by Django 5.2.8 on 2025-11-30 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('canteen', '0006_alter_orderitem_item_alter_order_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='item',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
